### ISSUE TITLE
API Down - Please Revive the Project

### ISSUE THREAD

**Issue by 0xshubhams** [naps62/ethglobal-lisbon#1]
Description: Hi there @naps62!

This project is fantastic and has been incredibly useful, but it seems a bit outdated. For example, calls to the API at https://api.thegraph.com/subgraphs/name/geraldhost/union are currently failing because the endpoint appears to be down.

Given how valuable this tool is for testing, I would love to see the project revived. It could be really helpful to many users if this issue with the API could be addressed, or if there's a plan to update the project for continued use.

Thanks for all your work, and I hope this project can continue to help others!

**Comment by naps62** [comment]
@shubham-giraft thanks. this project was a prototype specifically for ethglobal lisbon. if you like what it does, the good news is that you're probably gonna love the actual app I've been building since then (with the same feature demonstrated here, and much more): https://github.com/ethui/ethui
